language: java
script: ant

jdk:
  - oraclejdk11
  - oraclejdk9
  - openjdk11

os:
  - linux

# safelist
branches:
  only:
  - master
dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxml2-dev
