language: java
script: ant

jdk:
  - oraclejdk11
  - oraclejdk9
  - openjdk11

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install -y ant

# safelist
branches:
  only:
  - master
